name: Deploy to Github Pages

# on:
#   push:
#     branches:
#       - static-website
on: [push]
permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "lts/*"
      #     cache: "npm"
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run e2e:headless
      - name: Build
        run: |
          npm run build
          npm run export
      # - name: Deploy
      #   # https://github.com/JamesIves/github-pages-deploy-action
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: out