name: Run tests on merge

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Jest Unittests
        run: npm run test:ci
      - name: Run Cypress e2e tests
        run: npm run e2e:headless
        